name: GLaDOS checkin
on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: 30 1 * * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install depend
        run: npm i
      - name: Run checkin script
        run: node checkin.js
        env:
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
          COOKIES: ${{ secrets.COOKIES }}
