name: Every 25 minutes

on:
  schedule:
    - cron: '*/25 * * * *'

jobs:
  triggers:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: date && curl -sm 60 https://us-wsp.herokuapp.com
