name: Every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  triggers:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: date && curl -sm 60 https://kuayu.herokuapp.com
